Dyadic Trade Dataset
RandiLGarcia/dyadr pull request #22
Opened 2019-11-14 18:12 UTC by Lilyyyy54

Add Dyadic Trade Dataset to the Package

2019-11-18 11:57 UTC, RandiLGarcia commented
Hi Lily, for some reason it's not letting me complete your pull request.

2019-11-19 02:44 UTC, beanumber requested changes

2019-11-19 02:44 UTC, beanumber commented on DIADR.Rproj
> +Version: 1.0
@Lilyyyy54 please delete this file and commit the deletion. This shouldn't be here. 

Please also delete `.RData` and `dyadic_trade.RData`.

2019-11-19 02:44 UTC, beanumber commented on R/dyadic_trade-data.R
> +#' (\htef{http://www.correlatesofwar.org/data-sets/bilateral-trade})
You want `\url{}` here (not `\htef{}`)

2019-11-19 02:44 UTC, beanumber commented on R/dyadic_trade-data.R
> +#' (\htef{http://www.correlatesofwar.org/data-sets/bilateral-trade})
Please also add yourself to `DESCRIPTION` as a `ctb`.

2019-11-19 20:22 UTC, beanumber commented
@Lilyyyy54 please also delete `.RData` and add yourself to `DESCRIPTION` as a `ctb`.

2019-11-20 03:15 UTC, beanumber commented
@RandiLGarcia this looks good to merge, but there is a conflict causing by the `.RData` file that was part of #21 . I think you can resolve the conflict by deleting `.RData` manually on your end, and then merging the pull request. Let me know if I can help you.

2019-11-20 16:25 UTC, RandiLGarcia commented
@beanumber I need help. After I pulled I see carol's alliance data but not the .RData file in question.

2019-11-20 18:12 UTC, beanumber commented
OK, I can pay you a visit this afternoon.

2019-11-21 21:57 UTC, merged